
language: python
python:
  - "3.5"
sudo: required
services:
  - docker
before_install:
  - docker exec -it hardware_models_1 bash -c "pip install requests && pip install django-filter && pip install django-widget-tweaks && python manage.py makemigrations posts && python manage.py migrate && python manage.py loaddata /app/fixture/fixtures.json && mod_wsgi-express start-server --reload-on-changes hardware_models/wsgi.py"
script:
  - python ./hardware_models/manage.py test
