language: python

python:
  - "3.5"

sudo: required

services:
  - docker

before_install:
  - docker pull tp33/django

install:
  - pip install coveralls
  - pip install Django==1.13
  - pip install django-widget-tweaks
  - pip install django-filter
  - pip install pyyaml
  - pip install requests

script:
  - coverage run app/manage.py test
  - coverage report -m

after_success:
  coveralls
