kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka

es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"

batch:
   image: tp33/django
   container_name: batch
   links:
      - kafka:kafka
      - es:es
   volumes:
      - ./hardware_batch:/app
      - ./hardware_models/fixture:/app/fixture
   command: bash -c "python /app/runscripts.py"

models:
   image: tp33/django
   external_links:
      - mysql:db
   ports:
      - "8001:8000"
   volumes:
      - ./hardware_models:/app
   command: bash -c "pip install requests && pip install django-filter && pip install django-widget-tweaks && python manage.py makemigrations posts && python manage.py migrate && python manage.py loaddata /app/fixture/fixtures.json && mod_wsgi-express start-server --reload-on-changes hardware_models/wsgi.py"


exp:
   image: tp33/django
   links:
      - models:models-api
      - kafka:kafka
      - es:es
   ports:
      - "8002:8000"
   volumes:
      - ./hardware_exp:/app
   command: bash -c "pip install requests && pip install django-filter && pip install django-widget-tweaks && mod_wsgi-express start-server --reload-on-changes hardware_exp/wsgi.py"

web:
   image: tp33/django
   links:
      - exp:exp-api
   ports:
      - "8000:8000"
   volumes:
      - ./hardware_web:/app
   command: bash -c "pip install requests && pip install django-filter && pip install django-widget-tweaks &&  mod_wsgi-express start-server --reload-on-changes hardware_web/wsgi.py"

web2:
   image: tp33/django
   links:
      - exp:exp-api
   ports:
      - "8004:8000"
   volumes:
      - ./hardware_web:/app
   command: bash -c "pip install requests && pip install django-filter && pip install django-widget-tweaks &&  mod_wsgi-express start-server --reload-on-changes hardware_web/wsgi.py"

haproxy:
   image: haproxy:1.7
   links:
      - web
      - web2
   ports:
      - "80:8000"
   volumes:
      - ./:/app
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg


