models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./:/app
    ports:
      - "8001:8000"
    command: bash -c "mod_wsgi-express start-server --working-directory ~/github/petsitting --reload-on-changes ~github/petsitting/petsitting/wsgi.py"
