models:
   image: tp33/django
   external_links:
      - mysql:db
   ports:
      - "8001:8000"
   volumes:
      - ./:/app
   command: "mod_wsgi-express start-server --reload-on-changes app/hardware_models/wsgi.py"

exp:
   image: tp33/django
   links:
      - models:models-api
   ports:
      - "8002:8000"
   volumes:
      - ./:/app
   command: "mod_wsgi-express start-server --reload-on-changes app/hardware_exp/wsgi.py"

web:
   image: tp33/django
   links:
      - exp:exp-api
   ports:
      - "8000:8000"
   volumes:
      - ./:/app
   command: "mod_wsgi-express start-server --reload-on-changes app/hardware_web/wsgi.py"
