models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./:/app
    ports:
      - "8001:8000"
    command: bash -c "mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/petsitting/wsgi.py
            && python3 manage.py makemigrations && python3 manage.py migrate
            && python3 manage.py loaddata db.json"
