models:
   image: tp33/django
   external_links:
      - mysql:db
   ports:
      - "8001:8000"
   volumes:
      - ./hardware_models:/app
   command: bash -c "python manage.py makemigrations posts && python manage.py makemigrations login && python manage.py migrate && python manage.py loaddata db.json && mod_wsgi-express start-server --reload-on-changes hardware_models/wsgi.py"

exp:
   image: tp33/django
   links:
      - models:models-api
   ports:
      - "8002:8000"
   volumes:
      - ./hardware_exp:/app
   command: "mod_wsgi-express start-server --reload-on-changes hardware_exp/wsgi.py"

web:
   image: tp33/django
   links:
      - exp:exp-api
   ports:
      - "8000:8000"
   volumes:
      - ./hardware_web:/app
   command: "mod_wsgi-express start-server --reload-on-changes hardware_web/wsgi.py"
